# Generated by Django 3.2 on 2021-04-14 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('tipo_persona', models.TextField()),
                ('empresa', models.TextField(blank=True, null=True)),
                ('edad', models.PositiveIntegerField(max_length=3)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('clave', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('estado_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estado')),
            ],
        ),
    ]
